### ISSUE TITLE
TodoMVC: How to build and run?

### ISSUE THREAD

**Issue by malaire** [DioxusLabs/example-projects#15]
[TodoMVC](https://github.com/DioxusLabs/example-projects/tree/master/todomvc) doesn't have any documentation of how to build and run the example.

Simple `cargo run` fails with following error on Debian 11:

```
panicked at 'cannot call wasm-bindgen imported functions on non-wasm targets', /home/malaire/.cargo/registry/src/localhost-86e39b43d7f3e3e9/js-sys-0.3.59/src/lib.rs:5365:1
```

**Comment by AiyionPrime** [comment]
Did work: https://dioxuslabs.com/reference/platforms/web#getting-started-web
Good luck!

**Comment by vi** [comment]
Primary README contains this phrase:

> Each project has information on how to build/deploy.

Yet I don't see such information in TodoMVC's README.

> https://dioxuslabs.com/reference/platforms/web#getting-started-web

Error 404
Page not found

**Comment by zjp-CN** [comment]
The doc seems to be here https://dioxuslabs.com/docs/0.3/guide/en/getting_started/web.html

```shell
$ cd todomvc
$ dioxus serve
...
Dioxus @ v0.1.5 [20:19:54]

        > Local : http://localhost:8080/
        > NetWork : http://xxx:8080/

        > Profile : Debug
        > Hot Reload : Normal
        > Index Template : Custom [index.html]
        > URL Rewrite [index_on_404] : True

        > Build Time Use : 3937 millis

[INFO] A perfect compilation!
```

**It compiles, but the page is blank.**

<img src="https://github.com/DioxusLabs/example-projects/assets/25300418/2edfad58-bd90-4789-ae40-6c45183b4a87" width=50% height=50%>

**Comment by hpfmn** [comment]
I had the same issue removing the `index.html` helped

**Comment by magick93** [comment]
https://dioxuslabs.com/reference/platforms/web#getting-started-web is 404.

![image](https://github.com/DioxusLabs/example-projects/assets/2173213/b34bc9e3-3a6a-4080-81ce-b7e5a050989f)

The TodoMVC `docs` folder doesnt display in the browser. 

![image](https://github.com/DioxusLabs/example-projects/assets/2173213/31dd7135-13bb-46e1-9c2c-c59ec38324ca)


Just a simple markdown based instructions would be much easier.

**Comment by ealmloff** [comment]
> https://dioxuslabs.com/reference/platforms/web#getting-started-web is 404.
> 
> ![image](https://user-images.githubusercontent.com/2173213/282588626-b34bc9e3-3a6a-4080-81ce-b7e5a050989f.png)
> 
> The TodoMVC `docs` folder doesnt display in the browser.
> 
> ![image](https://user-images.githubusercontent.com/2173213/282588984-31dd7135-13bb-46e1-9c2c-c59ec38324ca.png)
> 
> Just a simple markdown based instructions would be much easier.

Where did you find that link? It should now be https://dioxuslabs.com/learn/0.4/getting_started/wasm

**Comment by ealmloff** [comment]
The docs are all markdown that lives here: https://github.com/DioxusLabs/docsite/tree/master/docs-src/0.4

**Comment by magick93** [comment]
Thanks @ealmloff 

I've read the getting started guides on https://dioxuslabs.com/learn/0.4/getting_started/, now I want to review some examples. 

Maybe adding the following to the  TodoMVC could help:

```
cargo install dioxus-cli
dx serve
```

**Comment by ealmloff** [comment]
> Thanks @ealmloff
> 
> I've read the getting started guides on https://dioxuslabs.com/learn/0.4/getting_started/, now I want to review some examples.
> 
> Maybe adding the following to the TodoMVC readme could help:
> 
> ```
> cargo install dioxus-cli
> dx serve
> ```

Adding something to any/all of the examples about how to run them would be great!
