### ISSUE TITLE
Duplicated examples in the main Dioxus repo

### ISSUE THREAD

**Issue by ealmloff** [DioxusLabs/example-projects#25]
## The Problem

There are several examples that are duplicated or remade in the main Dioxus repo:

- [TODOMVC](https://github.com/DioxusLabs/dioxus/blob/master/examples/todomvc.rs)
- [js framework benchmark](https://github.com/DioxusLabs/dioxus/blob/master/examples/framework_benchmark.rs)
- [file explorer](https://github.com/DioxusLabs/dioxus/blob/master/examples/file_explorer.rs)

## Proposed Solution

There are several advantages to having these examples in the main repo: 
- CI checks the examples to insure they are correct every release
- The examples in the main repo are more discoverable
- The main repo could be a single place to get all examples

We could move all examples into the main repo and depreciate this repo.

**Comment by jereanon** [comment]
I've addressed this issue in the following PR: https://github.com/DioxusLabs/dioxus/pull/1941

**Comment by jereanon** [comment]
Since this issue has been addressed, I would suggest depreciating this repository ahead of the 0.5 release.
