### ISSUE TITLE
Rewrite examples with Dioxus v0.5

### ISSUE THREAD

**Issue by tkr-sh** [DioxusLabs/example-projects#45]
Rewriting examples with v0.5 might help new comers ?

- [X] TodoMVC
- [X] iOS demo
- [x] File Explorer
- [ ] E-commerce
- [ ] Wifi Scanner
- [X] Weather App
- [X] Dog App

**Comment by ealmloff** [comment]
Some of the examples were updated and moved into the main repo in https://github.com/DioxusLabs/dioxus/pull/1941

**Comment by tkr-sh** [comment]
Oh, so only wifi scanner and file explorer remains ?
In that case, maybe we should add more examples ?

**Comment by ealmloff** [comment]
> Oh, so only wifi scanner and file explorer remains ? In that case, maybe we should add more examples and remove the ported ones ?

wifi-scanner, ecommerce-site, and the file-explorer were not ported. We should definitely remove the ported examples. Do you have specific examples you would like to add/see?

**Comment by tkr-sh** [comment]
Few ideas:
- Native components for mobile (map, camera (not supported in dioxus-std for now), etc.)
- A project that is responsive in cross-platform and that works on every platform with one codebase
- A youtube front-end in dioxus (I mean, it's possible and might not be thattt hard)
